sonar.projectKey=banking-system-application
sonar.projectName=Banking System Application
sonar.projectVersion=1.0

# Path to the source directories
sonar.sources=Bank System Application/src

# Path to the compiled classes
sonar.java.binaries=out

# Source encoding
sonar.sourceEncoding=UTF-8

# SonarQube server details
sonar.host.url=http://localhost:9000
sonar.login=admin
sonar.password=SRE-PROJECT-2026

